services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"  
    networks:
      - node-network
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "npm install && npm start"

  db:
    image: mysql:8.4
    container_name: db
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"
    networks:
      - node-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
